# https://openapi-generator.tech/docs/generators/php
inputSpec: AuthClient/spec.yaml
outputDir: AuthClient
generatorName: php
invokerPackage: MailevaApiAdapter\App\Client\AuthClient
packageName: AuthClient
srcBasePath: /
variableNamingConvention: camelCase
templateDir: /opt/openapi-custom/php
