# https://openapi-generator.tech/docs/generators/php
inputSpec: LrCoproClient/spec.yaml
outputDir: LrCoproClient
generatorName: php
invokerPackage: MailevaApiAdapter\App\Client\LrCoproClient
packageName: LrCoproClient
srcBasePath: /
variableNamingConvention: camelCase
