<?php
/**
 * EnvoiApi
 * PHP version 7.4
 *
 * @category Class
 * @package  MailevaApiAdapter\App\Client\SimpleSendingClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Maileva / Envoi et Suivi de Courriers simples
 *
 * API pour envoyer et suivre des courriers postaux.  Elle comprend les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options,  - suivre la production.  Pour connaitre les notifications (webhooks) concernées par cette API, consultez la documentation de l'API \"notification_center\".
 *
 * The version of the OpenAPI document: 2.6
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailevaApiAdapter\App\Client\SimpleSendingClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException;
use MailevaApiAdapter\App\Client\SimpleSendingClient\Configuration;
use MailevaApiAdapter\App\Client\SimpleSendingClient\HeaderSelector;
use MailevaApiAdapter\App\Client\SimpleSendingClient\ObjectSerializer;

/**
 * EnvoiApi Class Doc Comment
 *
 * @category Class
 * @package  MailevaApiAdapter\App\Client\SimpleSendingClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnvoiApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'sendingsGet' => [
            'application/json',
        ],
        'sendingsPost' => [
            'application/json',
        ],
        'sendingsSendingIdDelete' => [
            'application/json',
        ],
        'sendingsSendingIdGet' => [
            'application/json',
        ],
        'sendingsSendingIdPatch' => [
            'application/merge-patch+json',
        ],
        'sendingsSendingIdSubmitPost' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;

        $this->config->setHost($this->config->getHostFromSettings($hostIndex));
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation sendingsGet
     *
     * Liste des envois
     *
     * @param  float $startIndex Le premier élément à retourner (optional, default to 1)
     * @param  float $count Le nombre d&#39;élément à retourner (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsGet'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse
     */
    public function sendingsGet($startIndex = 1, $count = 50, string $contentType = self::contentTypes['sendingsGet'][0])
    {
        list($response) = $this->sendingsGetWithHttpInfo($startIndex, $count, $contentType);
        return $response;
    }

    /**
     * Operation sendingsGetWithHttpInfo
     *
     * Liste des envois
     *
     * @param  float $startIndex Le premier élément à retourner (optional, default to 1)
     * @param  float $count Le nombre d&#39;élément à retourner (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsGet'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendingsGetWithHttpInfo($startIndex = 1, $count = 50, string $contentType = self::contentTypes['sendingsGet'][0])
    {
        $request = $this->sendingsGetRequest($startIndex, $count, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendingsGetAsync
     *
     * Liste des envois
     *
     * @param  float $startIndex Le premier élément à retourner (optional, default to 1)
     * @param  float $count Le nombre d&#39;élément à retourner (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsGetAsync($startIndex = 1, $count = 50, string $contentType = self::contentTypes['sendingsGet'][0])
    {
        return $this->sendingsGetAsyncWithHttpInfo($startIndex, $count, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendingsGetAsyncWithHttpInfo
     *
     * Liste des envois
     *
     * @param  float $startIndex Le premier élément à retourner (optional, default to 1)
     * @param  float $count Le nombre d&#39;élément à retourner (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsGetAsyncWithHttpInfo($startIndex = 1, $count = 50, string $contentType = self::contentTypes['sendingsGet'][0])
    {
        $returnType = '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingsResponse';
        $request = $this->sendingsGetRequest($startIndex, $count, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendingsGet'
     *
     * @param  float $startIndex Le premier élément à retourner (optional, default to 1)
     * @param  float $count Le nombre d&#39;élément à retourner (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendingsGetRequest($startIndex = 1, $count = 50, string $contentType = self::contentTypes['sendingsGet'][0])
    {

        
        

        $resourcePath = '/sendings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $startIndex,
            'start_index', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $count,
            'count', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendingsPost
     *
     * Création d&#39;un envoi
     *
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingCreation $sendingCreation sendingCreation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsPost'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse
     */
    public function sendingsPost($sendingCreation = null, string $contentType = self::contentTypes['sendingsPost'][0])
    {
        list($response) = $this->sendingsPostWithHttpInfo($sendingCreation, $contentType);
        return $response;
    }

    /**
     * Operation sendingsPostWithHttpInfo
     *
     * Création d&#39;un envoi
     *
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingCreation $sendingCreation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsPost'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendingsPostWithHttpInfo($sendingCreation = null, string $contentType = self::contentTypes['sendingsPost'][0])
    {
        $request = $this->sendingsPostRequest($sendingCreation, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendingsPostAsync
     *
     * Création d&#39;un envoi
     *
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingCreation $sendingCreation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsPostAsync($sendingCreation = null, string $contentType = self::contentTypes['sendingsPost'][0])
    {
        return $this->sendingsPostAsyncWithHttpInfo($sendingCreation, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendingsPostAsyncWithHttpInfo
     *
     * Création d&#39;un envoi
     *
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingCreation $sendingCreation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsPostAsyncWithHttpInfo($sendingCreation = null, string $contentType = self::contentTypes['sendingsPost'][0])
    {
        $returnType = '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse';
        $request = $this->sendingsPostRequest($sendingCreation, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendingsPost'
     *
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingCreation $sendingCreation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendingsPostRequest($sendingCreation = null, string $contentType = self::contentTypes['sendingsPost'][0])
    {



        $resourcePath = '/sendings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sendingCreation)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($sendingCreation));
            } else {
                $httpBody = $sendingCreation;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendingsSendingIdDelete
     *
     * Suppression d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdDelete'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function sendingsSendingIdDelete($sendingId, string $contentType = self::contentTypes['sendingsSendingIdDelete'][0])
    {
        $this->sendingsSendingIdDeleteWithHttpInfo($sendingId, $contentType);
    }

    /**
     * Operation sendingsSendingIdDeleteWithHttpInfo
     *
     * Suppression d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdDelete'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendingsSendingIdDeleteWithHttpInfo($sendingId, string $contentType = self::contentTypes['sendingsSendingIdDelete'][0])
    {
        $request = $this->sendingsSendingIdDeleteRequest($sendingId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendingsSendingIdDeleteAsync
     *
     * Suppression d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsSendingIdDeleteAsync($sendingId, string $contentType = self::contentTypes['sendingsSendingIdDelete'][0])
    {
        return $this->sendingsSendingIdDeleteAsyncWithHttpInfo($sendingId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendingsSendingIdDeleteAsyncWithHttpInfo
     *
     * Suppression d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsSendingIdDeleteAsyncWithHttpInfo($sendingId, string $contentType = self::contentTypes['sendingsSendingIdDelete'][0])
    {
        $returnType = '';
        $request = $this->sendingsSendingIdDeleteRequest($sendingId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendingsSendingIdDelete'
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendingsSendingIdDeleteRequest($sendingId, string $contentType = self::contentTypes['sendingsSendingIdDelete'][0])
    {

        // verify the required parameter 'sendingId' is set
        if ($sendingId === null || (is_array($sendingId) && count($sendingId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendingId when calling sendingsSendingIdDelete'
            );
        }
        if (strlen($sendingId) > 40) {
            throw new \InvalidArgumentException('invalid length for "$sendingId" when calling EnvoiApi.sendingsSendingIdDelete, must be smaller than or equal to 40.');
        }
        

        $resourcePath = '/sendings/{sending_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($sendingId !== null) {
            $resourcePath = str_replace(
                '{' . 'sending_id' . '}',
                ObjectSerializer::toPathValue($sendingId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendingsSendingIdGet
     *
     * Détail d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdGet'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse
     */
    public function sendingsSendingIdGet($sendingId, string $contentType = self::contentTypes['sendingsSendingIdGet'][0])
    {
        list($response) = $this->sendingsSendingIdGetWithHttpInfo($sendingId, $contentType);
        return $response;
    }

    /**
     * Operation sendingsSendingIdGetWithHttpInfo
     *
     * Détail d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdGet'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendingsSendingIdGetWithHttpInfo($sendingId, string $contentType = self::contentTypes['sendingsSendingIdGet'][0])
    {
        $request = $this->sendingsSendingIdGetRequest($sendingId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendingsSendingIdGetAsync
     *
     * Détail d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsSendingIdGetAsync($sendingId, string $contentType = self::contentTypes['sendingsSendingIdGet'][0])
    {
        return $this->sendingsSendingIdGetAsyncWithHttpInfo($sendingId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendingsSendingIdGetAsyncWithHttpInfo
     *
     * Détail d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsSendingIdGetAsyncWithHttpInfo($sendingId, string $contentType = self::contentTypes['sendingsSendingIdGet'][0])
    {
        $returnType = '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse';
        $request = $this->sendingsSendingIdGetRequest($sendingId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendingsSendingIdGet'
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendingsSendingIdGetRequest($sendingId, string $contentType = self::contentTypes['sendingsSendingIdGet'][0])
    {

        // verify the required parameter 'sendingId' is set
        if ($sendingId === null || (is_array($sendingId) && count($sendingId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendingId when calling sendingsSendingIdGet'
            );
        }
        if (strlen($sendingId) > 40) {
            throw new \InvalidArgumentException('invalid length for "$sendingId" when calling EnvoiApi.sendingsSendingIdGet, must be smaller than or equal to 40.');
        }
        

        $resourcePath = '/sendings/{sending_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($sendingId !== null) {
            $resourcePath = str_replace(
                '{' . 'sending_id' . '}',
                ObjectSerializer::toPathValue($sendingId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendingsSendingIdPatch
     *
     * Modification partielle d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingUpdate $sendingUpdate sendingUpdate (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdPatch'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse
     */
    public function sendingsSendingIdPatch($sendingId, $sendingUpdate = null, string $contentType = self::contentTypes['sendingsSendingIdPatch'][0])
    {
        list($response) = $this->sendingsSendingIdPatchWithHttpInfo($sendingId, $sendingUpdate, $contentType);
        return $response;
    }

    /**
     * Operation sendingsSendingIdPatchWithHttpInfo
     *
     * Modification partielle d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingUpdate $sendingUpdate (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdPatch'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse|\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendingsSendingIdPatchWithHttpInfo($sendingId, $sendingUpdate = null, string $contentType = self::contentTypes['sendingsSendingIdPatch'][0])
    {
        $request = $this->sendingsSendingIdPatchRequest($sendingId, $sendingUpdate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendingsSendingIdPatchAsync
     *
     * Modification partielle d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingUpdate $sendingUpdate (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsSendingIdPatchAsync($sendingId, $sendingUpdate = null, string $contentType = self::contentTypes['sendingsSendingIdPatch'][0])
    {
        return $this->sendingsSendingIdPatchAsyncWithHttpInfo($sendingId, $sendingUpdate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendingsSendingIdPatchAsyncWithHttpInfo
     *
     * Modification partielle d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingUpdate $sendingUpdate (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsSendingIdPatchAsyncWithHttpInfo($sendingId, $sendingUpdate = null, string $contentType = self::contentTypes['sendingsSendingIdPatch'][0])
    {
        $returnType = '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingResponse';
        $request = $this->sendingsSendingIdPatchRequest($sendingId, $sendingUpdate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendingsSendingIdPatch'
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  \MailevaApiAdapter\App\Client\SimpleSendingClient\Model\SendingUpdate $sendingUpdate (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendingsSendingIdPatchRequest($sendingId, $sendingUpdate = null, string $contentType = self::contentTypes['sendingsSendingIdPatch'][0])
    {

        // verify the required parameter 'sendingId' is set
        if ($sendingId === null || (is_array($sendingId) && count($sendingId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendingId when calling sendingsSendingIdPatch'
            );
        }
        if (strlen($sendingId) > 40) {
            throw new \InvalidArgumentException('invalid length for "$sendingId" when calling EnvoiApi.sendingsSendingIdPatch, must be smaller than or equal to 40.');
        }
        


        $resourcePath = '/sendings/{sending_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($sendingId !== null) {
            $resourcePath = str_replace(
                '{' . 'sending_id' . '}',
                ObjectSerializer::toPathValue($sendingId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sendingUpdate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($sendingUpdate));
            } else {
                $httpBody = $sendingUpdate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendingsSendingIdSubmitPost
     *
     * Finalisation d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdSubmitPost'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function sendingsSendingIdSubmitPost($sendingId, string $contentType = self::contentTypes['sendingsSendingIdSubmitPost'][0])
    {
        $this->sendingsSendingIdSubmitPostWithHttpInfo($sendingId, $contentType);
    }

    /**
     * Operation sendingsSendingIdSubmitPostWithHttpInfo
     *
     * Finalisation d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdSubmitPost'] to see the possible values for this operation
     *
     * @throws \MailevaApiAdapter\App\Client\SimpleSendingClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendingsSendingIdSubmitPostWithHttpInfo($sendingId, string $contentType = self::contentTypes['sendingsSendingIdSubmitPost'][0])
    {
        $request = $this->sendingsSendingIdSubmitPostRequest($sendingId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailevaApiAdapter\App\Client\SimpleSendingClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendingsSendingIdSubmitPostAsync
     *
     * Finalisation d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdSubmitPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsSendingIdSubmitPostAsync($sendingId, string $contentType = self::contentTypes['sendingsSendingIdSubmitPost'][0])
    {
        return $this->sendingsSendingIdSubmitPostAsyncWithHttpInfo($sendingId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendingsSendingIdSubmitPostAsyncWithHttpInfo
     *
     * Finalisation d&#39;un envoi
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdSubmitPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendingsSendingIdSubmitPostAsyncWithHttpInfo($sendingId, string $contentType = self::contentTypes['sendingsSendingIdSubmitPost'][0])
    {
        $returnType = '';
        $request = $this->sendingsSendingIdSubmitPostRequest($sendingId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendingsSendingIdSubmitPost'
     *
     * @param  string $sendingId Identifiant d&#39;un envoi (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendingsSendingIdSubmitPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendingsSendingIdSubmitPostRequest($sendingId, string $contentType = self::contentTypes['sendingsSendingIdSubmitPost'][0])
    {

        // verify the required parameter 'sendingId' is set
        if ($sendingId === null || (is_array($sendingId) && count($sendingId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendingId when calling sendingsSendingIdSubmitPost'
            );
        }
        if (strlen($sendingId) > 40) {
            throw new \InvalidArgumentException('invalid length for "$sendingId" when calling EnvoiApi.sendingsSendingIdSubmitPost, must be smaller than or equal to 40.');
        }
        

        $resourcePath = '/sendings/{sending_id}/submit';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($sendingId !== null) {
            $resourcePath = str_replace(
                '{' . 'sending_id' . '}',
                ObjectSerializer::toPathValue($sendingId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
