# https://openapi-generator.tech/docs/generators/php
inputSpec: MailevaCoproClient/spec.yaml
outputDir: MailevaCoproClient
generatorName: php
invokerPackage: MailevaApiAdapter\App\Client\MailevaCoproClient
packageName: MailevaCoproClient
srcBasePath: /
variableNamingConvention: camelCase
templateDir: /opt/openapi-custom/php
