<?php
/**
 * SendingCreation
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MailevaApiAdapter\App\Client\LrelClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elle comprend les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options,  - suivre la production.  Pour connaitre les notifications (webhooks) concernées par cette API, consultez la documentation de l'API \"notification_center\".
 *
 * The version of the OpenAPI document: 2.5
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailevaApiAdapter\App\Client\LrelClient\Model;

use \ArrayAccess;
use \MailevaApiAdapter\App\Client\LrelClient\ObjectSerializer;

/**
 * SendingCreation Class Doc Comment
 *
 * @category Class
 * @description un envoi
 * @package  MailevaApiAdapter\App\Client\LrelClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SendingCreation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'sending_creation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'customId' => 'string',
        'customData' => 'string',
        'acknowledgementOfReceipt' => 'bool',
        'acknowledgementOfReceiptScanning' => 'bool',
        'colorPrinting' => 'bool',
        'duplexPrinting' => 'bool',
        'optionalAddressSheet' => 'bool',
        'notificationEmail' => 'string',
        'senderAddressLine1' => 'string',
        'senderAddressLine2' => 'string',
        'senderAddressLine3' => 'string',
        'senderAddressLine4' => 'string',
        'senderAddressLine5' => 'string',
        'senderAddressLine6' => 'string',
        'senderCountryCode' => '\MailevaApiAdapter\App\Client\LrelClient\Model\CountryCode',
        'archivingDuration' => 'int',
        'returnEnvelope' => '\MailevaApiAdapter\App\Client\LrelClient\Model\ReturnEnvelope'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'customId' => null,
        'customData' => null,
        'acknowledgementOfReceipt' => null,
        'acknowledgementOfReceiptScanning' => null,
        'colorPrinting' => null,
        'duplexPrinting' => null,
        'optionalAddressSheet' => null,
        'notificationEmail' => null,
        'senderAddressLine1' => null,
        'senderAddressLine2' => null,
        'senderAddressLine3' => null,
        'senderAddressLine4' => null,
        'senderAddressLine5' => null,
        'senderAddressLine6' => null,
        'senderCountryCode' => null,
        'archivingDuration' => null,
        'returnEnvelope' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
		'customId' => false,
		'customData' => false,
		'acknowledgementOfReceipt' => false,
		'acknowledgementOfReceiptScanning' => false,
		'colorPrinting' => false,
		'duplexPrinting' => false,
		'optionalAddressSheet' => false,
		'notificationEmail' => false,
		'senderAddressLine1' => false,
		'senderAddressLine2' => false,
		'senderAddressLine3' => false,
		'senderAddressLine4' => false,
		'senderAddressLine5' => false,
		'senderAddressLine6' => false,
		'senderCountryCode' => false,
		'archivingDuration' => false,
		'returnEnvelope' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'customId' => 'custom_id',
        'customData' => 'custom_data',
        'acknowledgementOfReceipt' => 'acknowledgement_of_receipt',
        'acknowledgementOfReceiptScanning' => 'acknowledgement_of_receipt_scanning',
        'colorPrinting' => 'color_printing',
        'duplexPrinting' => 'duplex_printing',
        'optionalAddressSheet' => 'optional_address_sheet',
        'notificationEmail' => 'notification_email',
        'senderAddressLine1' => 'sender_address_line_1',
        'senderAddressLine2' => 'sender_address_line_2',
        'senderAddressLine3' => 'sender_address_line_3',
        'senderAddressLine4' => 'sender_address_line_4',
        'senderAddressLine5' => 'sender_address_line_5',
        'senderAddressLine6' => 'sender_address_line_6',
        'senderCountryCode' => 'sender_country_code',
        'archivingDuration' => 'archiving_duration',
        'returnEnvelope' => 'return_envelope'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'customId' => 'setCustomId',
        'customData' => 'setCustomData',
        'acknowledgementOfReceipt' => 'setAcknowledgementOfReceipt',
        'acknowledgementOfReceiptScanning' => 'setAcknowledgementOfReceiptScanning',
        'colorPrinting' => 'setColorPrinting',
        'duplexPrinting' => 'setDuplexPrinting',
        'optionalAddressSheet' => 'setOptionalAddressSheet',
        'notificationEmail' => 'setNotificationEmail',
        'senderAddressLine1' => 'setSenderAddressLine1',
        'senderAddressLine2' => 'setSenderAddressLine2',
        'senderAddressLine3' => 'setSenderAddressLine3',
        'senderAddressLine4' => 'setSenderAddressLine4',
        'senderAddressLine5' => 'setSenderAddressLine5',
        'senderAddressLine6' => 'setSenderAddressLine6',
        'senderCountryCode' => 'setSenderCountryCode',
        'archivingDuration' => 'setArchivingDuration',
        'returnEnvelope' => 'setReturnEnvelope'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'customId' => 'getCustomId',
        'customData' => 'getCustomData',
        'acknowledgementOfReceipt' => 'getAcknowledgementOfReceipt',
        'acknowledgementOfReceiptScanning' => 'getAcknowledgementOfReceiptScanning',
        'colorPrinting' => 'getColorPrinting',
        'duplexPrinting' => 'getDuplexPrinting',
        'optionalAddressSheet' => 'getOptionalAddressSheet',
        'notificationEmail' => 'getNotificationEmail',
        'senderAddressLine1' => 'getSenderAddressLine1',
        'senderAddressLine2' => 'getSenderAddressLine2',
        'senderAddressLine3' => 'getSenderAddressLine3',
        'senderAddressLine4' => 'getSenderAddressLine4',
        'senderAddressLine5' => 'getSenderAddressLine5',
        'senderAddressLine6' => 'getSenderAddressLine6',
        'senderCountryCode' => 'getSenderCountryCode',
        'archivingDuration' => 'getArchivingDuration',
        'returnEnvelope' => 'getReturnEnvelope'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ARCHIVING_DURATION_3 = 3;
    public const ARCHIVING_DURATION_6 = 6;
    public const ARCHIVING_DURATION_10 = 10;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getArchivingDurationAllowableValues()
    {
        return [
            self::ARCHIVING_DURATION_3,
            self::ARCHIVING_DURATION_6,
            self::ARCHIVING_DURATION_10,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('customId', $data ?? [], null);
        $this->setIfExists('customData', $data ?? [], null);
        $this->setIfExists('acknowledgementOfReceipt', $data ?? [], true);
        $this->setIfExists('acknowledgementOfReceiptScanning', $data ?? [], false);
        $this->setIfExists('colorPrinting', $data ?? [], true);
        $this->setIfExists('duplexPrinting', $data ?? [], true);
        $this->setIfExists('optionalAddressSheet', $data ?? [], false);
        $this->setIfExists('notificationEmail', $data ?? [], null);
        $this->setIfExists('senderAddressLine1', $data ?? [], null);
        $this->setIfExists('senderAddressLine2', $data ?? [], null);
        $this->setIfExists('senderAddressLine3', $data ?? [], null);
        $this->setIfExists('senderAddressLine4', $data ?? [], null);
        $this->setIfExists('senderAddressLine5', $data ?? [], null);
        $this->setIfExists('senderAddressLine6', $data ?? [], null);
        $this->setIfExists('senderCountryCode', $data ?? [], null);
        $this->setIfExists('archivingDuration', $data ?? [], self::ARCHIVING_DURATION_3);
        $this->setIfExists('returnEnvelope', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 256)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 256.";
        }

        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['customId']) && (mb_strlen($this->container['customId']) > 38)) {
            $invalidProperties[] = "invalid value for 'customId', the character length must be smaller than or equal to 38.";
        }

        if (!is_null($this->container['customData']) && (mb_strlen($this->container['customData']) > 255)) {
            $invalidProperties[] = "invalid value for 'customData', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['notificationEmail'] === null) {
            $invalidProperties[] = "'notificationEmail' can't be null";
        }
        $allowedValues = $this->getArchivingDurationAllowableValues();
        if (!is_null($this->container['archivingDuration']) && !in_array($this->container['archivingDuration'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'archivingDuration', must be one of '%s'",
                $this->container['archivingDuration'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Nom de l'envoi
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 256)) {
            throw new \InvalidArgumentException('invalid length for $name when calling SendingCreation., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling SendingCreation., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets customId
     *
     * @return string|null
     */
    public function getCustomId()
    {
        return $this->container['customId'];
    }

    /**
     * Sets customId
     *
     * @param string|null $customId Identifiant de l'envoi défini par le client
     *
     * @return self
     */
    public function setCustomId($customId)
    {
        if (is_null($customId)) {
            throw new \InvalidArgumentException('non-nullable customId cannot be null');
        }
        if ((mb_strlen($customId) > 38)) {
            throw new \InvalidArgumentException('invalid length for $customId when calling SendingCreation., must be smaller than or equal to 38.');
        }

        $this->container['customId'] = $customId;

        return $this;
    }

    /**
     * Gets customData
     *
     * @return string|null
     */
    public function getCustomData()
    {
        return $this->container['customData'];
    }

    /**
     * Sets customData
     *
     * @param string|null $customData Information libre fournie par le client
     *
     * @return self
     */
    public function setCustomData($customData)
    {
        if (is_null($customData)) {
            throw new \InvalidArgumentException('non-nullable customData cannot be null');
        }
        if ((mb_strlen($customData) > 255)) {
            throw new \InvalidArgumentException('invalid length for $customData when calling SendingCreation., must be smaller than or equal to 255.');
        }

        $this->container['customData'] = $customData;

        return $this;
    }

    /**
     * Gets acknowledgementOfReceipt
     *
     * @return bool|null
     */
    public function getAcknowledgementOfReceipt()
    {
        return $this->container['acknowledgementOfReceipt'];
    }

    /**
     * Sets acknowledgementOfReceipt
     *
     * @param bool|null $acknowledgementOfReceipt Avis de réception (AR)
     *
     * @return self
     */
    public function setAcknowledgementOfReceipt($acknowledgementOfReceipt)
    {
        if (is_null($acknowledgementOfReceipt)) {
            throw new \InvalidArgumentException('non-nullable acknowledgementOfReceipt cannot be null');
        }
        $this->container['acknowledgementOfReceipt'] = $acknowledgementOfReceipt;

        return $this;
    }

    /**
     * Gets acknowledgementOfReceiptScanning
     *
     * @return bool|null
     */
    public function getAcknowledgementOfReceiptScanning()
    {
        return $this->container['acknowledgementOfReceiptScanning'];
    }

    /**
     * Sets acknowledgementOfReceiptScanning
     *
     * @param bool|null $acknowledgementOfReceiptScanning Gestion électronique des avis de réception (AR). Cette option indique que Maileva doit recevoir, numériser,  mettre en ligne l’image et archiver physiquement les Avis de Réception. Pour cela, la première ligne de l’adresse  de l’expéditeur sera conservée, mais les 5 autres lignes et le pays seront remplacés par l’adresse de Maileva.  Cette option nécessite que l’option avis de réception soit activée.
     *
     * @return self
     */
    public function setAcknowledgementOfReceiptScanning($acknowledgementOfReceiptScanning)
    {
        if (is_null($acknowledgementOfReceiptScanning)) {
            throw new \InvalidArgumentException('non-nullable acknowledgementOfReceiptScanning cannot be null');
        }
        $this->container['acknowledgementOfReceiptScanning'] = $acknowledgementOfReceiptScanning;

        return $this;
    }

    /**
     * Gets colorPrinting
     *
     * @return bool|null
     */
    public function getColorPrinting()
    {
        return $this->container['colorPrinting'];
    }

    /**
     * Sets colorPrinting
     *
     * @param bool|null $colorPrinting Impression couleur
     *
     * @return self
     */
    public function setColorPrinting($colorPrinting)
    {
        if (is_null($colorPrinting)) {
            throw new \InvalidArgumentException('non-nullable colorPrinting cannot be null');
        }
        $this->container['colorPrinting'] = $colorPrinting;

        return $this;
    }

    /**
     * Gets duplexPrinting
     *
     * @return bool|null
     */
    public function getDuplexPrinting()
    {
        return $this->container['duplexPrinting'];
    }

    /**
     * Sets duplexPrinting
     *
     * @param bool|null $duplexPrinting Impression recto verso
     *
     * @return self
     */
    public function setDuplexPrinting($duplexPrinting)
    {
        if (is_null($duplexPrinting)) {
            throw new \InvalidArgumentException('non-nullable duplexPrinting cannot be null');
        }
        $this->container['duplexPrinting'] = $duplexPrinting;

        return $this;
    }

    /**
     * Gets optionalAddressSheet
     *
     * @return bool|null
     */
    public function getOptionalAddressSheet()
    {
        return $this->container['optionalAddressSheet'];
    }

    /**
     * Sets optionalAddressSheet
     *
     * @param bool|null $optionalAddressSheet Feuille porte adresse optionnelle
     *
     * @return self
     */
    public function setOptionalAddressSheet($optionalAddressSheet)
    {
        if (is_null($optionalAddressSheet)) {
            throw new \InvalidArgumentException('non-nullable optionalAddressSheet cannot be null');
        }
        $this->container['optionalAddressSheet'] = $optionalAddressSheet;

        return $this;
    }

    /**
     * Gets notificationEmail
     *
     * @return string
     */
    public function getNotificationEmail()
    {
        return $this->container['notificationEmail'];
    }

    /**
     * Sets notificationEmail
     *
     * @param string $notificationEmail E-mail du destinataire des notifications
     *
     * @return self
     */
    public function setNotificationEmail($notificationEmail)
    {
        if (is_null($notificationEmail)) {
            throw new \InvalidArgumentException('non-nullable notificationEmail cannot be null');
        }
        $this->container['notificationEmail'] = $notificationEmail;

        return $this;
    }

    /**
     * Gets senderAddressLine1
     *
     * @return string|null
     */
    public function getSenderAddressLine1()
    {
        return $this->container['senderAddressLine1'];
    }

    /**
     * Sets senderAddressLine1
     *
     * @param string|null $senderAddressLine1 Ligne d'adresse n°1 (Société) de l'expéditeur
     *
     * @return self
     */
    public function setSenderAddressLine1($senderAddressLine1)
    {
        if (is_null($senderAddressLine1)) {
            throw new \InvalidArgumentException('non-nullable senderAddressLine1 cannot be null');
        }
        $this->container['senderAddressLine1'] = $senderAddressLine1;

        return $this;
    }

    /**
     * Gets senderAddressLine2
     *
     * @return string|null
     */
    public function getSenderAddressLine2()
    {
        return $this->container['senderAddressLine2'];
    }

    /**
     * Sets senderAddressLine2
     *
     * @param string|null $senderAddressLine2 Ligne d'adresse n°2 (Civilité, Prénom, Nom) de l'expéditeur
     *
     * @return self
     */
    public function setSenderAddressLine2($senderAddressLine2)
    {
        if (is_null($senderAddressLine2)) {
            throw new \InvalidArgumentException('non-nullable senderAddressLine2 cannot be null');
        }
        $this->container['senderAddressLine2'] = $senderAddressLine2;

        return $this;
    }

    /**
     * Gets senderAddressLine3
     *
     * @return string|null
     */
    public function getSenderAddressLine3()
    {
        return $this->container['senderAddressLine3'];
    }

    /**
     * Sets senderAddressLine3
     *
     * @param string|null $senderAddressLine3 Ligne d'adresse n°3 (Résidence, Bâtiement ...) de l'expéditeur
     *
     * @return self
     */
    public function setSenderAddressLine3($senderAddressLine3)
    {
        if (is_null($senderAddressLine3)) {
            throw new \InvalidArgumentException('non-nullable senderAddressLine3 cannot be null');
        }
        $this->container['senderAddressLine3'] = $senderAddressLine3;

        return $this;
    }

    /**
     * Gets senderAddressLine4
     *
     * @return string|null
     */
    public function getSenderAddressLine4()
    {
        return $this->container['senderAddressLine4'];
    }

    /**
     * Sets senderAddressLine4
     *
     * @param string|null $senderAddressLine4 Ligne d'adresse n°4 (N° et libellé de la voie) de l'expéditeur
     *
     * @return self
     */
    public function setSenderAddressLine4($senderAddressLine4)
    {
        if (is_null($senderAddressLine4)) {
            throw new \InvalidArgumentException('non-nullable senderAddressLine4 cannot be null');
        }
        $this->container['senderAddressLine4'] = $senderAddressLine4;

        return $this;
    }

    /**
     * Gets senderAddressLine5
     *
     * @return string|null
     */
    public function getSenderAddressLine5()
    {
        return $this->container['senderAddressLine5'];
    }

    /**
     * Sets senderAddressLine5
     *
     * @param string|null $senderAddressLine5 Ligne d'adresse n°5 (Lieu dit, BP...) de l'expéditeur
     *
     * @return self
     */
    public function setSenderAddressLine5($senderAddressLine5)
    {
        if (is_null($senderAddressLine5)) {
            throw new \InvalidArgumentException('non-nullable senderAddressLine5 cannot be null');
        }
        $this->container['senderAddressLine5'] = $senderAddressLine5;

        return $this;
    }

    /**
     * Gets senderAddressLine6
     *
     * @return string|null
     */
    public function getSenderAddressLine6()
    {
        return $this->container['senderAddressLine6'];
    }

    /**
     * Sets senderAddressLine6
     *
     * @param string|null $senderAddressLine6 Ligne d'adresse n°6 (Code postal et ville) de l'expéditeur
     *
     * @return self
     */
    public function setSenderAddressLine6($senderAddressLine6)
    {
        if (is_null($senderAddressLine6)) {
            throw new \InvalidArgumentException('non-nullable senderAddressLine6 cannot be null');
        }
        $this->container['senderAddressLine6'] = $senderAddressLine6;

        return $this;
    }

    /**
     * Gets senderCountryCode
     *
     * @return \MailevaApiAdapter\App\Client\LrelClient\Model\CountryCode|null
     */
    public function getSenderCountryCode()
    {
        return $this->container['senderCountryCode'];
    }

    /**
     * Sets senderCountryCode
     *
     * @param \MailevaApiAdapter\App\Client\LrelClient\Model\CountryCode|null $senderCountryCode senderCountryCode
     *
     * @return self
     */
    public function setSenderCountryCode($senderCountryCode)
    {
        if (is_null($senderCountryCode)) {
            throw new \InvalidArgumentException('non-nullable senderCountryCode cannot be null');
        }
        $this->container['senderCountryCode'] = $senderCountryCode;

        return $this;
    }

    /**
     * Gets archivingDuration
     *
     * @return int|null
     */
    public function getArchivingDuration()
    {
        return $this->container['archivingDuration'];
    }

    /**
     * Sets archivingDuration
     *
     * @param int|null $archivingDuration Durée d'archivage en années
     *
     * @return self
     */
    public function setArchivingDuration($archivingDuration)
    {
        if (is_null($archivingDuration)) {
            throw new \InvalidArgumentException('non-nullable archivingDuration cannot be null');
        }
        $allowedValues = $this->getArchivingDurationAllowableValues();
        if (!in_array($archivingDuration, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'archivingDuration', must be one of '%s'",
                    $archivingDuration,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['archivingDuration'] = $archivingDuration;

        return $this;
    }

    /**
     * Gets returnEnvelope
     *
     * @return \MailevaApiAdapter\App\Client\LrelClient\Model\ReturnEnvelope|null
     */
    public function getReturnEnvelope()
    {
        return $this->container['returnEnvelope'];
    }

    /**
     * Sets returnEnvelope
     *
     * @param \MailevaApiAdapter\App\Client\LrelClient\Model\ReturnEnvelope|null $returnEnvelope returnEnvelope
     *
     * @return self
     */
    public function setReturnEnvelope($returnEnvelope)
    {
        if (is_null($returnEnvelope)) {
            throw new \InvalidArgumentException('non-nullable returnEnvelope cannot be null');
        }
        $this->container['returnEnvelope'] = $returnEnvelope;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


