# https://openapi-generator.tech/docs/generators/php
inputSpec: SimpleSendingClient/spec.yaml
outputDir: SimpleSendingClient
generatorName: php
invokerPackage: MailevaApiAdapter\App\Client\SimpleSendingClient
packageName: SimpleSendingClient
srcBasePath: /
variableNamingConvention: camelCase
templateDir: /opt/openapi-custom/php
